# Generated by Django 4.2.7 on 2026-03-17 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_value', models.IntegerField(help_text='Raw MQ3 sensor value (0–4095)')),
                ('threshold', models.IntegerField(default=1500, help_text='Threshold used at detection time')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alcohol_alerts', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alcohol_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alcohol Alert',
                'verbose_name_plural': 'Alcohol Alerts',
                'ordering': ['-detected_at'],
            },
        ),
    ]
