# Generated by Django 4.2.7 on 2026-03-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcoholalert',
            name='alert_context',
            field=models.CharField(choices=[('DRIVING', 'Detected During Driving'), ('LOGIN', 'Login Cancelled — Pre-Drive Check')], default='DRIVING', help_text='Was this detected during driving or at login?', max_length=10),
        ),
    ]
