# Generated by Django 4.2.7 on 2025-12-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('seat_type', models.CharField(choices=[('REGULAR', 'Regular'), ('WOMEN', 'Women Only'), ('WHEELCHAIR', 'Wheelchair Accessible'), ('PREMIUM', 'Premium')], default='REGULAR', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('BLOCKED', 'Blocked')], default='AVAILABLE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_window', models.BooleanField(default=False)),
                ('is_aisle', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='transport.schedule')),
            ],
            options={
                'ordering': ['row', 'column'],
                'unique_together': {('schedule', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50, unique=True)),
                ('total_seats', models.IntegerField()),
                ('rows', models.IntegerField()),
                ('seats_per_row', models.IntegerField()),
                ('layout_config', models.JSONField(blank=True, default=dict, help_text='JSON configuration for seat layout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Seat Layouts',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seat_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transport.seatlayout'),
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=255)),
                ('passenger_age', models.IntegerField(blank=True, null=True)),
                ('passenger_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to='transport.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transport.seat')),
            ],
            options={
                'ordering': ['seat__seat_number'],
                'unique_together': {('booking', 'seat')},
            },
        ),
    ]
