# Generated by Django 4.2.7 on 2025-12-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_seat_seatlayout_vehicle_seat_layout_seatbooking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='seatbooking',
            name='seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.TextField(default='[]', help_text='JSON array of selected seat numbers'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='booked_seats',
            field=models.TextField(default='[]', help_text='JSON array of booked seat numbers'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_row_seats',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_rows',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='women_seats',
            field=models.TextField(default='[]', help_text='JSON array of seat numbers reserved for women'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seat_layout',
            field=models.CharField(choices=[('2-2', '2x2 Layout'), ('2-3', '2x3 Layout'), ('1-2', '1x2 Layout')], default='2-2', max_length=10),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='SeatBooking',
        ),
        migrations.DeleteModel(
            name='SeatLayout',
        ),
    ]
