# Generated by Django 4.2.7 on 2025-12-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_add_passenger_verification_to_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='related_booking',
            field=models.ForeignKey(blank=True, help_text="Link to passenger's booking (REQUIRED for passengers)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='transport.booking'),
        ),
    ]
