# Generated by Django 4.2.7 on 2025-12-26 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0003_alter_complaint_related_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Emergency message content')),
                ('hospital_info', models.TextField(blank=True, help_text='Hospital and medical facility information', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('total_recipients', models.IntegerField(default=0, help_text='Total passengers notified')),
                ('successful_sends', models.IntegerField(default=0, help_text='Successfully delivered messages')),
                ('failed_sends', models.IntegerField(default=0, help_text='Failed message deliveries')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_notifications', to='transport.schedule')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('is_alternate_number', models.BooleanField(default=False)),
                ('sent_status', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.booking')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='transport.emergencynotification')),
            ],
            options={
                'ordering': ['passenger_name'],
            },
        ),
    ]
