# Generated by Django 4.2.7 on 2025-12-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_seatbooking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_details',
            field=models.TextField(default='[]', help_text='JSON array of passenger details for each seat'),
        ),
    ]
