# Generated by Django 4.2.7 on 2025-12-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_emergencynotification_notificationrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='alternate_contact_number',
            field=models.CharField(blank=True, help_text='Alternate contact number for emergency notifications', max_length=15, null=True),
        ),
    ]
