# Generated by Django 4.2.7 on 2025-12-22 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_migrate_passenger_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin verified this is legitimate'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='issue_photo',
            field=models.ImageField(blank=True, help_text='Photo of the issue/problem', null=True, upload_to='complaints/issue_photos/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='issue_video',
            field=models.FileField(blank=True, help_text='Video of the issue/problem', null=True, upload_to='complaints/issue_videos/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='related_booking',
            field=models.ForeignKey(blank=True, help_text="Link to passenger's booking (for passengers)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='transport.booking'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='related_schedule',
            field=models.ForeignKey(blank=True, help_text='Link to schedule (for staff)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='transport.schedule'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='seat_photo',
            field=models.ImageField(blank=True, help_text='Photo of seat number (mandatory for passengers)', null=True, upload_to='complaints/seat_photos/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Which bus this complaint is about', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehicle'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='verification_notes',
            field=models.TextField(blank=True, help_text="Admin's verification notes", null=True),
        ),
    ]
