# Generated by Django 4.2.7 on 2025-12-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_booking_alternate_contact_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationrecipient',
            options={'ordering': ['seat_number', 'passenger_name']},
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='seat_number',
            field=models.CharField(blank=True, help_text='Seat number for sorting', max_length=10, null=True),
        ),
    ]
