# Generated by Django 4.2.7 on 2026-01-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_notificationrecipient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group/Family')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_group_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='triggers_female_restriction',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SeatRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('restriction_type', models.CharField(choices=[('WOMEN_RESERVED', 'Women Reserved Seat'), ('ADJACENT_TO_WOMEN_RESERVED', 'Adjacent to Women Reserved'), ('ADJACENT_TO_FEMALE', 'Adjacent to Female Passenger'), ('ADJACENT_TO_GROUP', 'Adjacent to Group Booking')], max_length=30)),
                ('is_female_only', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caused_by_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caused_restrictions', to='transport.booking')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'seat_number', 'restriction_type')},
            },
        ),
    ]
