# Generated by Django 4.2.7 on 2026-01-13 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0007_booking_booking_type_booking_is_group_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSTrackingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('NO_UPDATE', 'No GPS Update'), ('LOW_BATTERY', 'Low Battery'), ('GPS_DISABLED', 'GPS Disabled'), ('DEVICE_OFFLINE', 'Device Offline'), ('STALE_DATA', 'Stale Data')], max_length=20)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_alerts', to='transport.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed', models.FloatField(default=0)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='transport.schedule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['schedule', '-timestamp'], name='transport_b_schedul_373295_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed', models.FloatField(default=0, help_text='Speed in km/h')),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_moving', models.BooleanField(default=False)),
                ('battery_level', models.IntegerField(blank=True, help_text='Device battery percentage', null=True)),
                ('is_gps_enabled', models.BooleanField(default=True)),
                ('device_type', models.CharField(choices=[('DRIVER_PHONE', 'Driver Phone'), ('CONDUCTOR_PHONE', 'Conductor Phone'), ('GPS_DEVICE', 'GPS Hardware Device'), ('ADMIN', 'Admin')], default='DRIVER_PHONE', max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='transport.schedule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['schedule', '-timestamp'], name='transport_b_schedul_951039_idx')],
            },
        ),
    ]
