# Generated by Django 4.2.7 on 2026-01-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_gpstrackingalert_buslocationhistory_buslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
