# Generated by Django 4.2.7 on 2026-01-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_schedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslocationhistory',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
