# Generated by Django 4.2.7 on 2026-01-15 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0010_buslocationhistory_battery_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buslocationhistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Bus Location History', 'verbose_name_plural': 'Bus Location Histories'},
        ),
        migrations.AddField(
            model_name='buslocationhistory',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='buslocationhistory',
            name='device_type',
            field=models.CharField(choices=[('DRIVER_PHONE', 'Driver Phone'), ('CONDUCTOR_PHONE', 'Conductor Phone'), ('UNKNOWN', 'Unknown')], default='DRIVER_PHONE', max_length=20),
        ),
        migrations.AddField(
            model_name='buslocationhistory',
            name='is_gps_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buslocationhistory',
            name='is_moving',
            field=models.BooleanField(default=False, help_text='Whether the bus is moving'),
        ),
        migrations.AlterField(
            model_name='buslocationhistory',
            name='battery_level',
            field=models.IntegerField(blank=True, help_text='Device battery percentage (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='buslocationhistory',
            name='heading',
            field=models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True),
        ),
        migrations.AlterField(
            model_name='buslocationhistory',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buslocationhistory',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buslocationhistory',
            name='speed',
            field=models.FloatField(default=0, help_text='Speed in km/h'),
        ),
        migrations.AlterField(
            model_name='buslocationhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='buslocationhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='buslocationhistory',
            index=models.Index(fields=['updated_by', '-timestamp'], name='transport_b_updated_a20055_idx'),
        ),
    ]
