# Generated by Django 4.2.7 on 2026-01-22 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0011_alter_buslocationhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('order_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partial Refund')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CARD', 'Credit/Debit Card'), ('UPI', 'UPI'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet')], max_length=20, null=True)),
                ('card_last_4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_type', models.CharField(blank=True, max_length=20, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('is_mock', models.BooleanField(default=True)),
                ('mock_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('COMPLETED', 'Completed')], default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.CreateModel(
            name='PassengerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('passenger_age', models.IntegerField()),
                ('passenger_phone', models.CharField(max_length=15)),
                ('passenger_alternate_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_details_set', to='transport.booking')),
            ],
            options={
                'verbose_name': 'Passenger Detail',
                'verbose_name_plural': 'Passenger Details',
                'ordering': ['seat_number'],
            },
        ),
        migrations.CreateModel(
            name='MockRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_mock', models.BooleanField(default=True)),
                ('instant_refund', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_refunds', to='transport.booking')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_initiated_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='transport.mockpayment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='mock_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='transport.mockpayment'),
        ),
        migrations.AddIndex(
            model_name='mockpayment',
            index=models.Index(fields=['payment_id'], name='transport_m_payment_c62763_idx'),
        ),
        migrations.AddIndex(
            model_name='mockpayment',
            index=models.Index(fields=['order_id'], name='transport_m_order_i_48ddc2_idx'),
        ),
        migrations.AddIndex(
            model_name='mockpayment',
            index=models.Index(fields=['user', '-created_at'], name='transport_m_user_id_85fd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='mockpayment',
            index=models.Index(fields=['status'], name='transport_m_status_bada01_idx'),
        ),
    ]
