# Generated by Django 4.2.7 on 2026-03-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_booking_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buslocation',
            name='device_type',
            field=models.CharField(choices=[('DRIVER_PHONE', 'Driver Phone'), ('CONDUCTOR_PHONE', 'Conductor Phone'), ('GPS_HARDWARE', 'GPS Hardware Device'), ('ADMIN', 'Admin')], default='DRIVER_PHONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='buslocationhistory',
            name='device_type',
            field=models.CharField(choices=[('DRIVER_PHONE', 'Driver Phone'), ('CONDUCTOR_PHONE', 'Conductor Phone'), ('GPS_HARDWARE', 'GPS Hardware Device'), ('UNKNOWN', 'Unknown')], default='DRIVER_PHONE', max_length=20),
        ),
    ]
