# Generated by Django 4.2.7 on 2026-03-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_alter_buslocation_device_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPSTrackingAlert',
        ),
    ]
