# Generated by Django 4.2.7 on 2026-02-24 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HIGH', '🔥 Heart Rate Too High'), ('LOW', '❄️ Heart Rate Too Low')], max_length=10)),
                ('heart_rate', models.FloatField(help_text='BPM at time of alert')),
                ('threshold_low', models.FloatField(default=50)),
                ('threshold_high', models.FloatField(default=120)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_hr_alerts', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heart_rate_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Heart Rate Alert',
                'verbose_name_plural': 'Heart Rate Alerts',
                'ordering': ['-detected_at'],
            },
        ),
    ]
