# Generated by Django 4.2.7 on 2026-01-29 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0012_mockpayment_alter_booking_status_passengerdetails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrowsinessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_alerts', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Session duration in minutes')),
                ('avg_ear', models.FloatField(default=0, help_text='Average EAR during session')),
                ('min_ear', models.FloatField(default=0, help_text='Minimum EAR during session')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.schedule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DrowsinessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Low - Eye closure < 5 seconds'), ('MEDIUM', 'Medium - Eye closure 5-10 seconds'), ('HIGH', 'High - Eye closure 10-15 seconds'), ('CRITICAL', 'Critical - Eye closure > 15 seconds')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('eye_closure_duration', models.FloatField(help_text='Duration in seconds that eyes were closed')),
                ('ear_value', models.FloatField(help_text='Eye Aspect Ratio value at time of detection')),
                ('snapshot', models.ImageField(blank=True, help_text='Photo captured when drowsiness detected', null=True, upload_to='alerts/%Y/%m/%d/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude', max_digits=9, null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether email notification was sent')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When email was sent', null=True)),
                ('admin_notified', models.BooleanField(default=False, help_text='Whether admin was notified')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When drowsiness was detected')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When alert was acknowledged by admin', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When alert was marked as resolved', null=True)),
                ('admin_remarks', models.TextField(blank=True, help_text='Notes from admin about this alert')),
                ('driver', models.ForeignKey(help_text='Driver who triggered the alert', on_delete=django.db.models.deletion.CASCADE, related_name='drowsiness_alerts', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, help_text='Active schedule during alert (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.schedule')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Vehicle being driven (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.vehicle')),
            ],
            options={
                'verbose_name': 'Drowsiness Alert',
                'verbose_name_plural': 'Drowsiness Alerts',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['-detected_at'], name='drowsiness__detecte_26bbf2_idx'), models.Index(fields=['driver', '-detected_at'], name='drowsiness__driver__02f820_idx'), models.Index(fields=['status', '-detected_at'], name='drowsiness__status_0ca909_idx')],
            },
        ),
    ]
